server:
  port: 8082



#rocketmq????
rocketmq:
  #nameservice????????????????
  name-server: 127.0.0.1:9876
  #?????
  producer:
    #??
    group: anran-producer-group
    #????topic:tag?
    #topic
    topic: anran-topic
    #sync tag(????tag)
    sync-tag: anran-sync-tags
    #async tag(????tag)
    async-tag: anran-async-tags
    #oneway tag(????tag)
    oneway-tag: anran-oneway-tags

logging:
  file:
    path: /usr/log/mqproductservice/mqproductservice.log
  level:
    root: INFO
    com.anran.projectmanage.mapper: DEBUG