server:
  port: 8085

#rocketmq配置信息
rocketmq:
  #nameservice服务器地址（多个以英文逗号隔开）
  name-server: 127.0.0.1:9876
  #消费者配置
  consumer:
    #组名
    group: anran-consumer-group
    #监听主题
    topic: anran-topic
    #tags（监听多个tag时使用 || 进行分割，如果监听所有使用*或者不填）,支持sql过滤
    #    tags: anran-sync-tags||anran-async-tags||anran-oneway-tags
    tags: money > 5

logging:
  file:
    path: /usr/log/mqproductservice/mqproductservice.log
  level:
    root: INFO
    com.anran.projectmanage.mapper: DEBUG